// Generated by tools/sounds/build_sounds.py; edit that script, not this file.
import type { SoundEvent, Speaker } from "./cues";

type BySpeaker = Partial<Record<Speaker, string[]>>;

/** Recorded effect files per event; one is picked at random. */
export const SAMPLES: Partial<Record<SoundEvent, string[]>> = {
  "card": [
    "/sounds/sfx/card-1.mp3",
    "/sounds/sfx/card-2.mp3",
    "/sounds/sfx/card-3.mp3",
    "/sounds/sfx/card-4.mp3"
  ],
  "shuffle": [
    "/sounds/sfx/shuffle.mp3"
  ],
  "deal": [
    "/sounds/sfx/deal-1.mp3",
    "/sounds/sfx/deal-2.mp3"
  ],
  "truco": [
    "/sounds/sfx/truco.mp3"
  ],
  "seis": [
    "/sounds/sfx/seis.mp3"
  ],
  "nove": [
    "/sounds/sfx/nove.mp3"
  ],
  "doze": [
    "/sounds/sfx/doze.mp3"
  ],
  "accept": [
    "/sounds/sfx/accept-1.mp3",
    "/sounds/sfx/accept-2.mp3",
    "/sounds/sfx/accept-3.mp3"
  ],
  "run": [
    "/sounds/sfx/run-1.mp3",
    "/sounds/sfx/run-2.mp3",
    "/sounds/sfx/run-3.mp3",
    "/sounds/sfx/run-4.mp3"
  ],
  "roundWin": [
    "/sounds/sfx/roundWin.mp3"
  ],
  "roundLose": [
    "/sounds/sfx/roundLose.mp3"
  ],
  "roundTie": [
    "/sounds/sfx/roundTie.mp3"
  ],
  "handWin": [
    "/sounds/sfx/handWin-1.mp3",
    "/sounds/sfx/handWin-2.mp3"
  ],
  "handLose": [
    "/sounds/sfx/handLose-1.mp3",
    "/sounds/sfx/handLose-2.mp3"
  ],
  "handDraw": [
    "/sounds/sfx/handDraw.mp3"
  ],
  "mao11": [
    "/sounds/sfx/mao11.mp3"
  ],
  "matchWin": [
    "/sounds/sfx/matchWin.mp3"
  ],
  "matchLose": [
    "/sounds/sfx/matchLose.mp3"
  ]
};

/** Generated voice files per event and speaker. */
export const VOICE_FILES: Partial<Record<SoundEvent, BySpeaker>> = {
  "truco": {
    "p0": [
      "/sounds/voice/p0/truco-1.mp3",
      "/sounds/voice/p0/truco-2.mp3"
    ],
    "p1": [
      "/sounds/voice/p1/truco-1.mp3",
      "/sounds/voice/p1/truco-2.mp3",
      "/sounds/voice/p1/truco-3.mp3"
    ]
  },
  "seis": {
    "p0": [
      "/sounds/voice/p0/seis-1.mp3",
      "/sounds/voice/p0/seis-2.mp3"
    ],
    "p1": [
      "/sounds/voice/p1/seis-1.mp3",
      "/sounds/voice/p1/seis-2.mp3"
    ]
  },
  "nove": {
    "p0": [
      "/sounds/voice/p0/nove-1.mp3",
      "/sounds/voice/p0/nove-2.mp3"
    ],
    "p1": [
      "/sounds/voice/p1/nove-1.mp3",
      "/sounds/voice/p1/nove-2.mp3"
    ]
  },
  "doze": {
    "p0": [
      "/sounds/voice/p0/doze-1.mp3",
      "/sounds/voice/p0/doze-2.mp3"
    ],
    "p1": [
      "/sounds/voice/p1/doze-1.mp3",
      "/sounds/voice/p1/doze-2.mp3"
    ]
  },
  "accept": {
    "p0": [
      "/sounds/voice/p0/accept-1.mp3",
      "/sounds/voice/p0/accept-2.mp3",
      "/sounds/voice/p0/accept-3.mp3"
    ],
    "p1": [
      "/sounds/voice/p1/accept-1.mp3",
      "/sounds/voice/p1/accept-2.mp3",
      "/sounds/voice/p1/accept-3.mp3"
    ]
  },
  "run": {
    "p0": [
      "/sounds/voice/p0/run-1.mp3",
      "/sounds/voice/p0/run-2.mp3"
    ],
    "p1": [
      "/sounds/voice/p1/run-1.mp3",
      "/sounds/voice/p1/run-2.mp3",
      "/sounds/voice/p1/run-3.mp3"
    ]
  },
  "matchWin": {
    "p1": [
      "/sounds/voice/p1/matchWin-1.mp3",
      "/sounds/voice/p1/matchWin-2.mp3"
    ]
  },
  "matchLose": {
    "p1": [
      "/sounds/voice/p1/matchLose-1.mp3",
      "/sounds/voice/p1/matchLose-2.mp3"
    ]
  }
};

/** The same lines as text, for the browser's speech synthesis when a file is missing. */
export const VOICE_LINES: Partial<Record<SoundEvent, BySpeaker>> = {
  "truco": {
    "p0": [
      "Truco!",
      "Truco, marreco!"
    ],
    "p1": [
      "Truco!",
      "Truco, patinho!",
      "Truco, ladrão!"
    ]
  },
  "seis": {
    "p0": [
      "Seis!",
      "Seis, ladrão!"
    ],
    "p1": [
      "Seis!",
      "Seis, malandro!"
    ]
  },
  "nove": {
    "p0": [
      "Nove!",
      "Nove, que eu tô com tudo!"
    ],
    "p1": [
      "Nove!",
      "Nove, e não chora!"
    ]
  },
  "doze": {
    "p0": [
      "Doze!",
      "Doze, vamo acabar com isso!"
    ],
    "p1": [
      "Doze!",
      "Doze, pra fechar!"
    ]
  },
  "accept": {
    "p0": [
      "Cai dentro!",
      "Vem!",
      "Aceito!"
    ],
    "p1": [
      "Cai dentro!",
      "Vem!",
      "Bora!"
    ]
  },
  "run": {
    "p0": [
      "Tô fora.",
      "Corri."
    ],
    "p1": [
      "Tô fora.",
      "Essa eu deixo.",
      "Fica pra próxima."
    ]
  },
  "matchWin": {
    "p1": [
      "Foi sorte, malandro.",
      "Hoje não foi meu dia."
    ]
  },
  "matchLose": {
    "p1": [
      "Vai treinar, patinho!",
      "Volta pro bar, marreco!"
    ]
  }
};
